# -*- coding: utf-8 -*-
"""LLM_Prompt_Library_with_LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Ogx94VIcjudrGe27-w5kLl8PKAAjkjB
"""

# ================= LLM Library with LangChain + Groq =================

import os, sys, json, getpass, subprocess

# ---- 1) Install packages only if missing ----
for mod, pkg in [("langchain_core", "langchain-core"),
                 ("langchain_groq", "langchain-groq"),
                 ("requests", "requests")]:
    try:
        __import__(mod)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

import requests
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser
from langchain_groq import ChatGroq

OUT = "llm_prompt_library"
os.makedirs(OUT, exist_ok=True)

# ---- 2) API key: env -> Colab Secrets -> hidden prompt ----
def get_api_key():
    key = os.environ.get("GROQ_API_KEY")
    if key:
        return key.strip()
    try:
        from google.colab import userdata
        key = userdata.get("GROQ_API_KEY")
        if key:
            return key.strip()
    except Exception:
        pass
    key = getpass.getpass("Enter NEW GROQ_API_KEY (hidden): ").strip()
    if not key:
        raise SystemExit("No API key provided.")
    return key

API_KEY = get_api_key()
os.environ["GROQ_API_KEY"] = API_KEY

# ---- 3) Get live model list from Groq, build candidate list ----
PREFERRED = ["llama-3.3-70b-versatile", "openai/gpt-oss-120b", "openai/gpt-oss-20b",
             "llama-3.1-8b-instant", "qwen/qwen3.6-27b", "qwen/qwen3.8-27b"]
SKIP = ("whisper", "tts", "guard", "playai", "orpheus", "embed", "compound")

try:
    r = requests.get("https://api.groq.com/openai/v1/models",
                     headers={"Authorization": f"Bearer {API_KEY}"}, timeout=20)
    r.raise_for_status()
    live = [m["id"] for m in r.json().get("data", [])]
except Exception as e:
    raise SystemExit(f"Groq model list fetch failed. Key galat/revoked ho sakti hai: {e}")

print("Available models:", live)
candidates = [m for m in PREFERRED if m in live] + \
             [m for m in live if m not in PREFERRED and not any(s in m.lower() for s in SKIP)]
if not candidates:
    raise SystemExit("Is key par koi chat model nahi mila.")

# ---- 4) Prompt library (reusable, named, versioned) ----
PROMPT_LIBRARY = {
    "sentiment_classifier": {
        "version": "1.0", "output": "json",
        "system": ("You are a customer feedback analyst. Classify the review. "
                   "Reply ONLY with valid JSON with keys: sentiment (positive/negative/neutral), "
                   "confidence (0-1), reason (max 15 words)."),
        "human": "Review: {text}"},
    "insight_summarizer": {
        "version": "1.0", "output": "text",
        "system": ("You are a senior data analyst. Summarise the findings for business "
                   "stakeholders in exactly 3 bullet points: finding, impact, recommendation. "
                   "Use only the numbers given. Do not invent figures."),
        "human": "Findings: {text}"},
    "sql_explainer": {
        "version": "1.0", "output": "text",
        "system": ("You explain SQL to non-technical business users in simple English, "
                   "in at most 4 sentences. Say what the query returns and why it is useful."),
        "human": "SQL query:\n{text}"},
    "churn_retention_advisor": {
        "version": "1.0", "output": "text",
        "system": ("You are a retention strategist. Given churn analysis results, suggest 3 "
                   "practical retention actions, each tied to a number in the input. Be concise."),
        "human": "Churn results: {text}"},
}
with open(f"{OUT}/prompt_library.json", "w", encoding="utf-8") as f:
    json.dump(PROMPT_LIBRARY, f, indent=2, ensure_ascii=False)

# ---- 5) LangChain chain (prompt | llm | parser) ----
def build_chain(name, model_id):
    cfg = PROMPT_LIBRARY[name]
    prompt = ChatPromptTemplate.from_messages([("system", cfg["system"]), ("human", cfg["human"])])
    parser = JsonOutputParser() if cfg["output"] == "json" else StrOutputParser()
    llm = ChatGroq(model=model_id, temperature=0, max_retries=2)
    return prompt | llm | parser

# Tries each candidate model until one works
def run_prompt(name, text):
    last_err = None
    for model_id in candidates:
        try:
            return build_chain(name, model_id).invoke({"text": text}), model_id
        except Exception as e:
            last_err = f"{type(e).__name__}: {str(e)[:200]}"
            continue
    return {"error": last_err}, None

# ---- 6) Demo run ----
TESTS = {
    "sentiment_classifier": "The delivery was two days late and the packaging was damaged.",
    "insight_summarizer": ("58% of 50,000 customers are in the At Risk RFM group; "
                           "Random Forest reached 91.6% accuracy and 93% precision for churn."),
    "sql_explainer": ("SELECT category, SUM(price * quantity) AS revenue FROM products "
                      "GROUP BY category ORDER BY revenue DESC LIMIT 5;"),
    "churn_retention_advisor": ("At Risk group = 58% (29,094 customers); "
                                "class-balanced Logistic Regression churn recall = 73.8%."),
}

results = {}
for name, text in TESTS.items():
    out, used = run_prompt(name, text)
    print(f"\n=== {name} (v{PROMPT_LIBRARY[name]['version']}) | model: {used} ===")
    print(json.dumps(out, indent=2, ensure_ascii=False) if isinstance(out, dict) else out)
    results[name] = {"input": text, "model": used, "output": out}

with open(f"{OUT}/results.json", "w", encoding="utf-8") as f:
    json.dump(results, f, indent=2, ensure_ascii=False)
print(f"\nSaved: {OUT}/prompt_library.json and {OUT}/results.json")